# Generated by Django 5.1.6 on 2025-03-04 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articleblog", "0002_category_article_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="text",
            new_name="content",
        ),
    ]
