# Generated by Django 5.1.6 on 2025-03-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articleblog", "0003_rename_text_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
    ]
