# Generated by Django 5.1.6 on 2025-03-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articleblog", "0004_comment_flagged"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="articleblog.category"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="flagged",
            field=models.BooleanField(default=True),
        ),
    ]
